name: CI
on: pull_request
permissions: write-all
jobs:
  build:
    runs-on: ubuntu-latest
    name: build job
    steps:
      - name: use actions
        uses: actions/checkout@v3
      - name: run build
        run: gradle clean build

      - name: Upload test.exec
        uses: 'actions/upload-artifact@v3'
        with:
          name: testexecution
          path: ${{ github.workspace }}/build/jacoco

  checkstyle:
    runs-on: ubuntu-latest
    name: Checkstyle job
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run check style
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          checkstyle_config: config/checkstyle/checkstyle.xml

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: download test.exec
        uses: 'actions/download-artifact@v3'
        with:
          name: testexecution
          path: ${{ github.workspace }}/build/jacoco

      - name: Run Coverage
        run: gradle jacocoTestReport

      - name: Jacoco Report to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          debug-mode: true
          title: Code Coverage
          update-comment: true